apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: nginx-app
    location: NA

spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2

  - name: nginx-container2
    image: nginx:1.14.2
