apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
spec:
  containers:
    - name: node-app-container
      image: kunal770/node-sample

      # env plain text
      # env:
      #   - name: PORT
      #     value: "3000"

      # external ENV config map
      # envFrom:
      #   - configMapRef:
      #       name: node-config

      # Use both in one
      env:
        - name: NODE_ENV
          value: deploy
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: node-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: node-config
              key: NODE_ENV
