apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: kunal770/ubuntu-sleeper
      # command: ["sleep"]
      # args: ["15"]
      # command: ["sleep", "5"]
      command:
        - "sleep"
        - "1"
